/**
 * Generate China province SVG paths from GeoJSON using d3-geo
 * China Albers equal-area conic projection
 * Standard parallels: 25°N, 47°N, Central meridian: 105°E
 */
const fs = require('fs');
const path = require('path');
const d3 = require('d3-geo');
const cm = require('china-map-geojson');

// China Albers equal-area conic projection
const projection = d3.geoConicEqualArea()
  .parallels([25, 47])
  .rotate([-105, 0])
  .fitSize([774, 569], cm.ChinaData);

const pathGen = d3.geoPath().projection(projection);
const features = cm.ChinaData.features;

const regionMap = {
  '广东': ['pearl-river-delta', ['Electronics','Furniture','Apparel'], 4],
  '广西': ['pearl-river-delta', ['Food','Raw materials'], 1],
  '海南': ['pearl-river-delta', ['Tourism','Agriculture'], 1],
  '香港': ['pearl-river-delta', ['Finance','Trade hub'], 4],
  '澳门': ['pearl-river-delta', ['Tourism','Gaming'], 2],
  '上海': ['yangtze-river-delta', ['Trade HQ','Semiconductors'], 3],
  '江苏': ['yangtze-river-delta', ['Machinery','Electronics'], 3],
  '浙江': ['yangtze-river-delta', ['Textiles','Home goods'], 3],
  '北京': ['beijing-tianjin-hebei', ['Biotech','Aerospace'], 2],
  '天津': ['beijing-tianjin-hebei', ['Port logistics','Automotive'], 2],
  '河北': ['beijing-tianjin-hebei', ['Pharma','Industrial systems'], 2],
  '河南': ['central-china', ['Assembly','Food processing'], 2],
  '湖北': ['central-china', ['Auto','Optoelectronics'], 2],
  '湖南': ['central-china', ['Machinery','Food'], 2],
  '安徽': ['central-china', ['Displays','Automotive'], 2],
  '江西': ['central-china', ['Mining','Electronics'], 1],
  '四川': ['sichuan-chongqing', ['Electronics','Talent hub'], 3],
  '重庆': ['sichuan-chongqing', ['Automotive','Rail logistics'], 3],
  '福建': ['fujian-coast', ['Footwear','Tea','Stone'], 3],
  '台湾': ['other', ['Semiconductors','Electronics'], 0],
};

const idMap = {
  '北京': 'beijing','天津': 'tianjin','河北': 'hebei','山西': 'shanxi',
  '内蒙古': 'neimenggu','辽宁': 'liaoning','吉林': 'jilin','黑龙江': 'heilongjiang',
  '上海': 'shanghai','江苏': 'jiangsu','浙江': 'zhejiang','安徽': 'anhui',
  '福建': 'fujian','江西': 'jiangxi','山东': 'shandong','河南': 'henan',
  '湖北': 'hubei','湖南': 'hunan','广东': 'guangdong','广西': 'guangxi',
  '海南': 'hainan','重庆': 'chongqing','四川': 'sichuan','贵州': 'guizhou',
  '云南': 'yunnan','西藏': 'xizang','陕西': 'shaanxi','甘肃': 'gansu',
  '青海': 'qinghai','宁夏': 'ningxia','新疆': 'xinjiang','台湾': 'taiwan',
  '香港': 'hong-kong','澳门': 'macau',
};

let lines = [];
lines.push('// Auto-generated by scripts/gen-map.js');
lines.push('// All 34 provinces via China Albers conic equal-area projection');
lines.push('export interface ChinaProvincePath {');
lines.push('  id: string;');
lines.push('  name: string;');
lines.push('  path: string;');
lines.push('  regionSlug: string;');
lines.push('  industries: string[];');
lines.push('  density: number;');
lines.push('}');
lines.push('');
lines.push('export const CHINA_VIEWBOX = "0 0 774 569";');
lines.push('');
lines.push('export const chinaProvinces: ChinaProvincePath[] = [');

features.forEach(f => {
  const name = f.properties.name;
  const id = idMap[name] || 'unknown';
  const region = regionMap[name] || ['other', [], 0];
  
  const svgPath = pathGen(f);
  if (!svgPath) {
    console.log('⚠ No path for:', name);
    return;
  }
  
  lines.push('  {');
  lines.push('    id: "' + id + '",');
  lines.push('    name: "' + name + '",');
  lines.push('    path: "' + svgPath + '",');
  lines.push('    regionSlug: "' + region[0] + '",');
  lines.push('    industries: ' + JSON.stringify(region[1]) + ',');
  lines.push('    density: ' + region[2] + ',');
  lines.push('  },');
});

lines.push('];');

const outPath = path.join(__dirname, '..', 'src', 'data', 'china-provinces.ts');
fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log('✅ Generated', features.length, 'provinces');
console.log('File:', outPath);
